export const GET_PRODUCTS_PENDING = 'GET_PRODUCTS_PENDING;';
export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS';
export const GET_PRODUCTS_ERROR = 'GET_PRODUCTS_ERROR';

export const GETBYID_PRODUCTS_PENDING = 'GETBYID_PRODUCTS_PENDING;';
export const GETBYID_PRODUCTS_SUCCESS = 'GETBYID_PRODUCTS_SUCCESS';
export const GETBYID_PRODUCTS_ERROR = 'GETBYID_PRODUCTS_ERROR';

export const DELETE_PRODUCTS_PENDING = 'DELETE_PRODUCTS_PENDING;';
export const DELETE_PRODUCTS_SUCCESS = 'DELETE_PRODUCTS_SUCCESS';
export const DELETE_PRODUCTS_ERROR = 'DELETE_PRODUCTS_ERROR';

export const POST_PRODUCTS_PENDING = 'POST_PRODUCTS_PENDING;';
export const POST_PRODUCTS_SUCCESS = 'POST_PRODUCTS_SUCCESS';
export const POST_PRODUCTS_ERROR = 'POST_PRODUCTS_ERROR';

export const EDIT_PRODUCTS_PENDING = 'EDIT_PRODUCTS_PENDING;';
export const EDIT_PRODUCTS_SUCCESS = 'EDIT_PRODUCTS_SUCCESS';
export const EDIT_PRODUCTS_ERROR = 'EDIT_PRODUCTS_ERROR';